[workspace]
resolver = "2"
members = [ "crates/app", "crates/engine", "crates/math", "crates/renderer", "crates/shaders", "crates/voxel" ]

[workspace.package]
version = "0.1.0"
edition = "2021"

[workspace.dependencies]
anyhow = "1.0"
log = "0.4"
env_logger = "0.10"
pollster = "0.4.0"